- name: Ansible facts
  hosts: windows-vm1
  gather_facts: yes
  become: false

  tasks:
    - name: Display all facts
      debug:
        var: ansible_facts

    - name: Display specific facts
      debug:
        msg: |
          IPv4 Address: {{ ansible_facts['ip_addresses'] | default('Not available') }}
          FQDN: {{ ansible_facts['fqdn'] | default('Not available') }}
          Short Hostname: {{ ansible_facts['hostname'] | default('Not available') }}

