---
- name: Install and Manage Apache and MariaDB Services
  hosts: linux-vm2
  become: yes
  tasks:
    - name: Install Apache and MariaDB
      yum:
        name:
          - httpd
          - mariadb-server
        state: present

    - name: Enable Apache service to start on boot
      systemd:
        name: httpd
        enabled: yes
        state: started

    - name: Enable MariaDB service to start on boot
      systemd:
        name: mariadb
        enabled: yes
        state: started

